version: '3'

services:
  app:
    image: node:18 
    container_name: mainvest-app
    volumes:
      - ./app:/app
      - ./server:/server
      - /node_modules
    working_dir: /app
    ports:
      - 4200:4200
      - 5300:5300
    depends_on:
      - mainvest-database
    networks:
      - mainvest-net
    command: tail -f /dev/null
  mainvest-database:
    image: postgres
    container_name: mainvest-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mainvest
      POSTGRES_DB: mainvest
      PGPORT: 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - mainvest-net
networks:
  mainvest-net:
    driver: bridge
